version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
      time: 05:00
      timezone: Europe/Paris
  - package-ecosystem: github-actions
    directory: /sync/.github/workflows
    schedule:
      interval: daily
      time: 05:00
      timezone: Europe/Paris
